nav:
  Home: /
  About: /about/
  Writing: /archives/
  Projects: http://github.com/amendgit

projects_url: http://github.com/amendgit

customize:
    gravatar:
        email: 
    logo:
        enabled: false
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: http://github.com/amendgit
        twitter: /
        facebook: /
        linkedin: http://www.linkedin.com/in/amendgit
    post_count: 7
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics
    gentie_productKey: dd35274a0a4a4fa78803c58ca5824094

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
